### ISSUE TITLE
TypeError while loading LSP server

### ISSUE THREAD

**Issue by ChZiegelt** [largeBIGsnooze/soase2-plugin-vscode#1]
` [ 🛈 Info - 11:29:44 PM]: Initializing server...
 [ 🛈 Info - 11:29:44 PM]: Jabberwocky: Sins 2 Language Server initialized, version: 0.4.3
 [ 🛈 Info - 11:29:44 PM]: Operational files:  {
    "0": ".mod_meta_data",
    "1": "player",
    "2": "weapon",
    "3": "unit_item",
    "4": "buff",
    "5": "entity_manifest",
    "6": "research_subject",
    "7": "formation",
    "8": "exotic",
    "9": "flight_pattern",
    "10": "ability",
    "11": "action_data_source",
    "12": "npc_reward",
    "13": "unit",
    "14": "unit_skin",
    "15": "localized_text",
    "16": "mesh_material",
    "54": "named_colors.named_colors",
    "55": "icon",
    "56": "player_icon",
    "57": "player_portrait",
    "58": "player_color_group",
    "59": "skybox",
    "60": "font",
    "61": "gravity_well_props",
    "62": "cursor",
    "63": "sound",
    "64": "texture_animation",
    "65": "brush",
    "66": "death_sequence",
    "67": "death_sequence_group",
    "68": "welcome_message",
    "69": "gdpr_accept_data",
    "gui": {},
    "button_styles": {},
    "label_styles": {},
    "list_box_styles": {},
    "text_entry_box_styles": {},
    "drop_box_styles": {},
    "reflect_box_styles": {},
    "uniforms": {
        "17": "weapon.uniforms",
        "18": "strikecraft.uniforms",
        "19": "action.uniforms",
        "20": "attack_target_type_group.uniforms",
        "21": "culture.uniforms",
        "22": "debris.uniforms",
        "23": "formation.uniforms",
        "24": "front_end.uniforms",
        "25": "future_orbit.uniforms",
        "26": "unit_tag.uniforms",
        "27": "target_filter.uniforms",
        "28": "player_color.uniforms",
        "29": "music.uniforms",
        "30": "galaxy_generator.uniforms",
        "31": "game_renderer.uniforms",
        "32": "user_interface.uniforms",
        "33": "unit_build.uniforms",
        "34": "unit_mutation.uniforms",
        "35": "unit_bar.uniforms",
        "36": "gui.uniforms",
        "37": "unit.uniforms",
        "38": "research.uniforms",
        "39": "scenario.uniforms",
        "40": "player_ai.uniforms",
        "41": "planet_track.uniforms",
        "42": "planet.uniforms",
        "43": "loot.uniforms",
        "44": "main_view.uniforms",
        "45": "notification.uniforms",
        "46": "player.uniforms",
        "47": "exotic.uniforms",
        "48": "special_operation_unit.uniforms",
        "49": "hud_skin.uniforms",
        "50": "random_skybox_filling.uniforms"
    },
    "effects": {
        "51": "exhaust_trail_effect",
        "52": "beam_effect",
        "53": "shield_effect"
    }
}
c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97
const enumerate = ({ items: [...items], isIntType = false }) => {
                            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at enumerate (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97:29)
    at initCache (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:258:32)
    at module.exports (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:710:5)
    at Lsp.initialized (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\lsp-server.js:73:45)

Node.js v20.9.0
[Error - 11:29:44 PM] Server process exited with code 1.
[Info  - 11:29:44 PM] Connection to server got closed. Server will restart.
true
 [ 🛈 Info - 11:29:45 PM]: Initializing server...
 [ 🛈 Info - 11:29:45 PM]: Jabberwocky: Sins 2 Language Server initialized, version: 0.4.3
 [ 🛈 Info - 11:29:45 PM]: Operational files:  {
    "0": ".mod_meta_data",
    "1": "player",
    "2": "weapon",
    "3": "unit_item",
    "4": "buff",
    "5": "entity_manifest",
    "6": "research_subject",
    "7": "formation",
    "8": "exotic",
    "9": "flight_pattern",
    "10": "ability",
    "11": "action_data_source",
    "12": "npc_reward",
    "13": "unit",
    "14": "unit_skin",
    "15": "localized_text",
    "16": "mesh_material",
    "54": "named_colors.named_colors",
    "55": "icon",
    "56": "player_icon",
    "57": "player_portrait",
    "58": "player_color_group",
    "59": "skybox",
    "60": "font",
    "61": "gravity_well_props",
    "62": "cursor",
    "63": "sound",
    "64": "texture_animation",
    "65": "brush",
    "66": "death_sequence",
    "67": "death_sequence_group",
    "68": "welcome_message",
    "69": "gdpr_accept_data",
    "gui": {},
    "button_styles": {},
    "label_styles": {},
    "list_box_styles": {},
    "text_entry_box_styles": {},
    "drop_box_styles": {},
    "reflect_box_styles": {},
    "uniforms": {
        "17": "weapon.uniforms",
        "18": "strikecraft.uniforms",
        "19": "action.uniforms",
        "20": "attack_target_type_group.uniforms",
        "21": "culture.uniforms",
        "22": "debris.uniforms",
        "23": "formation.uniforms",
        "24": "front_end.uniforms",
        "25": "future_orbit.uniforms",
        "26": "unit_tag.uniforms",
        "27": "target_filter.uniforms",
        "28": "player_color.uniforms",
        "29": "music.uniforms",
        "30": "galaxy_generator.uniforms",
        "31": "game_renderer.uniforms",
        "32": "user_interface.uniforms",
        "33": "unit_build.uniforms",
        "34": "unit_mutation.uniforms",
        "35": "unit_bar.uniforms",
        "36": "gui.uniforms",
        "37": "unit.uniforms",
        "38": "research.uniforms",
        "39": "scenario.uniforms",
        "40": "player_ai.uniforms",
        "41": "planet_track.uniforms",
        "42": "planet.uniforms",
        "43": "loot.uniforms",
        "44": "main_view.uniforms",
        "45": "notification.uniforms",
        "46": "player.uniforms",
        "47": "exotic.uniforms",
        "48": "special_operation_unit.uniforms",
        "49": "hud_skin.uniforms",
        "50": "random_skybox_filling.uniforms"
    },
    "effects": {
        "51": "exhaust_trail_effect",
        "52": "beam_effect",
        "53": "shield_effect"
    }
}
c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97
const enumerate = ({ items: [...items], isIntType = false }) => {
                            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at enumerate (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97:29)
    at initCache (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:258:32)
    at module.exports (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:710:5)
    at Lsp.initialized (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\lsp-server.js:73:45)

Node.js v20.9.0
[Error - 11:29:45 PM] Server process exited with code 1.
[Info  - 11:29:45 PM] Connection to server got closed. Server will restart.
true
 [ 🛈 Info - 11:29:45 PM]: Initializing server...
 [ 🛈 Info - 11:29:45 PM]: Jabberwocky: Sins 2 Language Server initialized, version: 0.4.3
 [ 🛈 Info - 11:29:45 PM]: Operational files:  {
    "0": ".mod_meta_data",
    "1": "player",
    "2": "weapon",
    "3": "unit_item",
    "4": "buff",
    "5": "entity_manifest",
    "6": "research_subject",
    "7": "formation",
    "8": "exotic",
    "9": "flight_pattern",
    "10": "ability",
    "11": "action_data_source",
    "12": "npc_reward",
    "13": "unit",
    "14": "unit_skin",
    "15": "localized_text",
    "16": "mesh_material",
    "54": "named_colors.named_colors",
    "55": "icon",
    "56": "player_icon",
    "57": "player_portrait",
    "58": "player_color_group",
    "59": "skybox",
    "60": "font",
    "61": "gravity_well_props",
    "62": "cursor",
    "63": "sound",
    "64": "texture_animation",
    "65": "brush",
    "66": "death_sequence",
    "67": "death_sequence_group",
    "68": "welcome_message",
    "69": "gdpr_accept_data",
    "gui": {},
    "button_styles": {},
    "label_styles": {},
    "list_box_styles": {},
    "text_entry_box_styles": {},
    "drop_box_styles": {},
    "reflect_box_styles": {},
    "uniforms": {
        "17": "weapon.uniforms",
        "18": "strikecraft.uniforms",
        "19": "action.uniforms",
        "20": "attack_target_type_group.uniforms",
        "21": "culture.uniforms",
        "22": "debris.uniforms",
        "23": "formation.uniforms",
        "24": "front_end.uniforms",
        "25": "future_orbit.uniforms",
        "26": "unit_tag.uniforms",
        "27": "target_filter.uniforms",
        "28": "player_color.uniforms",
        "29": "music.uniforms",
        "30": "galaxy_generator.uniforms",
        "31": "game_renderer.uniforms",
        "32": "user_interface.uniforms",
        "33": "unit_build.uniforms",
        "34": "unit_mutation.uniforms",
        "35": "unit_bar.uniforms",
        "36": "gui.uniforms",
        "37": "unit.uniforms",
        "38": "research.uniforms",
        "39": "scenario.uniforms",
        "40": "player_ai.uniforms",
        "41": "planet_track.uniforms",
        "42": "planet.uniforms",
        "43": "loot.uniforms",
        "44": "main_view.uniforms",
        "45": "notification.uniforms",
        "46": "player.uniforms",
        "47": "exotic.uniforms",
        "48": "special_operation_unit.uniforms",
        "49": "hud_skin.uniforms",
        "50": "random_skybox_filling.uniforms"
    },
    "effects": {
        "51": "exhaust_trail_effect",
        "52": "beam_effect",
        "53": "shield_effect"
    }
}
c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97
const enumerate = ({ items: [...items], isIntType = false }) => {
                            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at enumerate (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97:29)
    at initCache (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:258:32)
    at module.exports (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:710:5)
    at Lsp.initialized (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\lsp-server.js:73:45)

Node.js v20.9.0
[Error - 11:29:45 PM] Server process exited with code 1.
[Info  - 11:29:45 PM] Connection to server got closed. Server will restart.
true
 [ 🛈 Info - 11:29:45 PM]: Initializing server...
 [ 🛈 Info - 11:29:45 PM]: Jabberwocky: Sins 2 Language Server initialized, version: 0.4.3
 [ 🛈 Info - 11:29:45 PM]: Operational files:  {
    "0": ".mod_meta_data",
    "1": "player",
    "2": "weapon",
    "3": "unit_item",
    "4": "buff",
    "5": "entity_manifest",
    "6": "research_subject",
    "7": "formation",
    "8": "exotic",
    "9": "flight_pattern",
    "10": "ability",
    "11": "action_data_source",
    "12": "npc_reward",
    "13": "unit",
    "14": "unit_skin",
    "15": "localized_text",
    "16": "mesh_material",
    "54": "named_colors.named_colors",
    "55": "icon",
    "56": "player_icon",
    "57": "player_portrait",
    "58": "player_color_group",
    "59": "skybox",
    "60": "font",
    "61": "gravity_well_props",
    "62": "cursor",
    "63": "sound",
    "64": "texture_animation",
    "65": "brush",
    "66": "death_sequence",
    "67": "death_sequence_group",
    "68": "welcome_message",
    "69": "gdpr_accept_data",
    "gui": {},
    "button_styles": {},
    "label_styles": {},
    "list_box_styles": {},
    "text_entry_box_styles": {},
    "drop_box_styles": {},
    "reflect_box_styles": {},
    "uniforms": {
        "17": "weapon.uniforms",
        "18": "strikecraft.uniforms",
        "19": "action.uniforms",
        "20": "attack_target_type_group.uniforms",
        "21": "culture.uniforms",
        "22": "debris.uniforms",
        "23": "formation.uniforms",
        "24": "front_end.uniforms",
        "25": "future_orbit.uniforms",
        "26": "unit_tag.uniforms",
        "27": "target_filter.uniforms",
        "28": "player_color.uniforms",
        "29": "music.uniforms",
        "30": "galaxy_generator.uniforms",
        "31": "game_renderer.uniforms",
        "32": "user_interface.uniforms",
        "33": "unit_build.uniforms",
        "34": "unit_mutation.uniforms",
        "35": "unit_bar.uniforms",
        "36": "gui.uniforms",
        "37": "unit.uniforms",
        "38": "research.uniforms",
        "39": "scenario.uniforms",
        "40": "player_ai.uniforms",
        "41": "planet_track.uniforms",
        "42": "planet.uniforms",
        "43": "loot.uniforms",
        "44": "main_view.uniforms",
        "45": "notification.uniforms",
        "46": "player.uniforms",
        "47": "exotic.uniforms",
        "48": "special_operation_unit.uniforms",
        "49": "hud_skin.uniforms",
        "50": "random_skybox_filling.uniforms"
    },
    "effects": {
        "51": "exhaust_trail_effect",
        "52": "beam_effect",
        "53": "shield_effect"
    }
}
c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97
const enumerate = ({ items: [...items], isIntType = false }) => {
                            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at enumerate (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97:29)
    at initCache (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:258:32)
    at module.exports (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:710:5)
    at Lsp.initialized (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\lsp-server.js:73:45)

Node.js v20.9.0
[Error - 11:29:45 PM] Server process exited with code 1.
[Info  - 11:29:45 PM] Connection to server got closed. Server will restart.
true
 [ 🛈 Info - 11:29:46 PM]: Initializing server...
 [ 🛈 Info - 11:29:46 PM]: Jabberwocky: Sins 2 Language Server initialized, version: 0.4.3
 [ 🛈 Info - 11:29:46 PM]: Operational files:  {
    "0": ".mod_meta_data",
    "1": "player",
    "2": "weapon",
    "3": "unit_item",
    "4": "buff",
    "5": "entity_manifest",
    "6": "research_subject",
    "7": "formation",
    "8": "exotic",
    "9": "flight_pattern",
    "10": "ability",
    "11": "action_data_source",
    "12": "npc_reward",
    "13": "unit",
    "14": "unit_skin",
    "15": "localized_text",
    "16": "mesh_material",
    "54": "named_colors.named_colors",
    "55": "icon",
    "56": "player_icon",
    "57": "player_portrait",
    "58": "player_color_group",
    "59": "skybox",
    "60": "font",
    "61": "gravity_well_props",
    "62": "cursor",
    "63": "sound",
    "64": "texture_animation",
    "65": "brush",
    "66": "death_sequence",
    "67": "death_sequence_group",
    "68": "welcome_message",
    "69": "gdpr_accept_data",
    "gui": {},
    "button_styles": {},
    "label_styles": {},
    "list_box_styles": {},
    "text_entry_box_styles": {},
    "drop_box_styles": {},
    "reflect_box_styles": {},
    "uniforms": {
        "17": "weapon.uniforms",
        "18": "strikecraft.uniforms",
        "19": "action.uniforms",
        "20": "attack_target_type_group.uniforms",
        "21": "culture.uniforms",
        "22": "debris.uniforms",
        "23": "formation.uniforms",
        "24": "front_end.uniforms",
        "25": "future_orbit.uniforms",
        "26": "unit_tag.uniforms",
        "27": "target_filter.uniforms",
        "28": "player_color.uniforms",
        "29": "music.uniforms",
        "30": "galaxy_generator.uniforms",
        "31": "game_renderer.uniforms",
        "32": "user_interface.uniforms",
        "33": "unit_build.uniforms",
        "34": "unit_mutation.uniforms",
        "35": "unit_bar.uniforms",
        "36": "gui.uniforms",
        "37": "unit.uniforms",
        "38": "research.uniforms",
        "39": "scenario.uniforms",
        "40": "player_ai.uniforms",
        "41": "planet_track.uniforms",
        "42": "planet.uniforms",
        "43": "loot.uniforms",
        "44": "main_view.uniforms",
        "45": "notification.uniforms",
        "46": "player.uniforms",
        "47": "exotic.uniforms",
        "48": "special_operation_unit.uniforms",
        "49": "hud_skin.uniforms",
        "50": "random_skybox_filling.uniforms"
    },
    "effects": {
        "51": "exhaust_trail_effect",
        "52": "beam_effect",
        "53": "shield_effect"
    }
}
c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97
const enumerate = ({ items: [...items], isIntType = false }) => {
                            ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at enumerate (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\definitions\data_types.js:97:29)
    at initCache (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:258:32)
    at module.exports (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\cache.js:710:5)
    at Lsp.initialized (c:\Users\Christian\.vscode\extensions\cyno-studios.soase2-plugin-vscode-0.4.3\server\lsp-server.js:73:45)

Node.js v20.9.0
[Error - 11:29:46 PM] Server process exited with code 1.
[Error - 11:29:46 PM] The Jabberwocky: Sins 2 Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
`

**Comment by ChZiegelt** [comment]
Hi, maybe I'm doing something wrong - but do not get the extension to run

**Comment by largeBIGsnooze** [comment]
Hey! The extension is currently outdated and is being updated to fit the current version of the game.

**Comment by ChZiegelt** [comment]
ah - ok - sorry didn't see this :-)

**Comment by ChZiegelt** [comment]
I was just wondering how to setup the basics when starting a small mod.
Just created a folder inside the AppData\Local\sins2\mods folder and copied in the .vscode and json_schemas folders from sins2 github repo

**Comment by largeBIGsnooze** [comment]
Once I finish updating the extension you won't need to deal with any schemas as they're gonna be built-in 👍
