### ISSUE TITLE
Question : How to refer to ints in another json file

### ISSUE THREAD

**Issue by darthun** [largeBIGsnooze/soase2-plugin-vscode#2]
Hi,
Sorry for opening an issue, I'm not sure how to contact you.

I'm trying to mod sins2 and on this repo's main page, you have a picture where "starting_units_in_hyperspace" : {},

I have come to understand that {} is used by the game engine to mean to use a variable's value. 
However, I haven't found how to refer to a value defined somewhere else. 

I was hoping your usage of this meant maybe you know how to point to any generic values defined elsewhere in json. 
I know that the ':' symbol is used to mean 'don't interpolate, just use as-is' but i haven't found a way to specify 'go fetch the value from this variable at this location' 

Please let know if you know how to use variables and a better way to contact you in the future :)

Thank you !

**Comment by largeBIGsnooze** [comment]
Hey, you can get in touch here: [https://discord.gg/cRm5UdmhsJ](https://discord.gg/cRm5UdmhsJ)

As per your issue, the curly braces {} are an object definition, it has no relation to any type of variable within the modding context, it's simply a part of the text format the engine serializes its game data in

You can learn about the format here: [https://www.json.org/json-en.html](https://www.json.org/json-en.html)
